-- =====================================================================
-- Phase 4: TOU charge calculator + billing period consumption
--
-- DT_INTERVAL_TOU_TAGGED joins interval reads to the meter's rate plan
--   via CUSTOMER.RATE_PLAN_ID, then aligns to TOU_RATE_WINDOW by day_type
--   + local time band.
-- DT_INTERVAL_CHARGE_LINE multiplies kwh and kw by the rates.
-- DT_BILLING_PERIOD_CONSUMPTION joins daily rollups to BILLING_PERIOD.
-- =====================================================================

USE DATABASE AMI_DEMO;
USE SCHEMA AMI_MART;

CREATE OR REPLACE DYNAMIC TABLE DT_INTERVAL_TOU_TAGGED
  TARGET_LAG = '15 minutes'
  WAREHOUSE = AMI_DT_WH
AS
SELECT
  i.METER_ID,
  i.READ_TS,
  i.KWH_DELIVERED AS KWH,
  i.DEMAND_KW,
  i.UTILITY_TERRITORY,
  td.DAY_TYPE,
  td.SEASON,
  c.RATE_PLAN_ID,
  rw.RATE_WINDOW_ID,
  rw.TOU_BUCKET,
  rw.ENERGY_RATE_PER_KWH,
  rw.DEMAND_RATE_PER_KW
FROM AMI_CURATED.INTERVAL_READ_15MIN i
JOIN AMI_CURATED.METER_SERVICE_POINT_LINK l
  ON l.METER_ID = i.METER_ID AND l.IS_CURRENT
JOIN AMI_CURATED.CUSTOMER c
  ON c.CUSTOMER_ID = l.CUSTOMER_ID
JOIN AMI_CURATED.TIME_DIM td
  ON td.TS_UTC = i.READ_TS
JOIN AMI_CURATED.TOU_RATE_WINDOW rw
  ON rw.RATE_PLAN_ID = c.RATE_PLAN_ID
 AND rw.DAY_TYPE    = td.DAY_TYPE
 AND (rw.SEASON = 'ALL' OR rw.SEASON = td.SEASON)
 AND td.LOCAL_TIME >= rw.START_TIME
 AND td.LOCAL_TIME <= rw.END_TIME
WHERE i.VEE_STATUS IN ('VALID','ESTIMATED');


CREATE OR REPLACE DYNAMIC TABLE DT_INTERVAL_CHARGE_LINE
  TARGET_LAG = '15 minutes'
  WAREHOUSE = AMI_DT_WH
AS
SELECT
  METER_ID,
  READ_TS,
  UTILITY_TERRITORY,
  RATE_PLAN_ID,
  RATE_WINDOW_ID,
  TOU_BUCKET,
  KWH,
  DEMAND_KW,
  ENERGY_RATE_PER_KWH,
  DEMAND_RATE_PER_KW,
  (KWH * ENERGY_RATE_PER_KWH)::NUMBER(14,4)             AS ENERGY_CHARGE,
  (DEMAND_KW * DEMAND_RATE_PER_KW / 96.0)::NUMBER(14,4) AS DEMAND_CHARGE
FROM AMI_MART.DT_INTERVAL_TOU_TAGGED;


CREATE OR REPLACE DYNAMIC TABLE DT_BILLING_PERIOD_CONSUMPTION
  TARGET_LAG = '30 minutes'
  WAREHOUSE = AMI_DT_WH
AS
SELECT
  bp.BILLING_PERIOD_ID,
  bp.CIS_ACCOUNT_ID,
  bp.SERVICE_POINT_ID,
  m.METER_ID,
  bp.START_DATE,
  bp.END_DATE,
  SUM(d.KWH_DELIVERED)   AS KWH_TOTAL,
  SUM(d.KWH_RECEIVED)    AS KWH_RECEIVED,
  SUM(d.KWH_NET)         AS KWH_NET,
  MAX(d.MAX_DEMAND_KW)   AS MAX_DEMAND_KW,
  AVG(d.COMPLETENESS_PCT)::NUMBER(5,2) AS COMPLETENESS_PCT,
  AVG(d.VEE_PASS_PCT)::NUMBER(5,2)     AS VEE_PASS_PCT,
  CASE WHEN AVG(d.COMPLETENESS_PCT) >= 99 AND AVG(d.VEE_PASS_PCT) >= 97 THEN TRUE ELSE FALSE END AS IS_BILLING_READY
FROM AMI_CURATED.BILLING_PERIOD bp
JOIN AMI_CURATED.METER m ON m.SERVICE_POINT_ID = bp.SERVICE_POINT_ID
JOIN AMI_CURATED.DT_DAILY_ROLLUP d
  ON d.METER_ID = m.METER_ID
 AND d.ROLLUP_TS BETWEEN bp.START_DATE AND bp.END_DATE
GROUP BY bp.BILLING_PERIOD_ID, bp.CIS_ACCOUNT_ID, bp.SERVICE_POINT_ID,
         m.METER_ID, bp.START_DATE, bp.END_DATE;


-- Reconciliation view between interval-derived and CIS-reported
CREATE OR REPLACE VIEW V_BILLING_RECONCILIATION AS
SELECT
  bpc.BILLING_PERIOD_ID,
  bpc.CIS_ACCOUNT_ID,
  bpc.METER_ID,
  bpc.KWH_TOTAL             AS INTERVAL_SUM_KWH,
  bp.CIS_BILLED_KWH,
  (bpc.KWH_TOTAL - COALESCE(bp.CIS_BILLED_KWH, bpc.KWH_TOTAL)) AS VARIANCE_KWH,
  CASE WHEN bp.CIS_BILLED_KWH IS NULL OR bp.CIS_BILLED_KWH = 0 THEN NULL
       ELSE ABS(bpc.KWH_TOTAL - bp.CIS_BILLED_KWH) / bp.CIS_BILLED_KWH * 100 END AS VARIANCE_PCT,
  bpc.COMPLETENESS_PCT,
  bpc.IS_BILLING_READY
FROM AMI_MART.DT_BILLING_PERIOD_CONSUMPTION bpc
JOIN AMI_CURATED.BILLING_PERIOD bp
  ON bp.BILLING_PERIOD_ID = bpc.BILLING_PERIOD_ID;
