-- =====================================================================
-- Phase 1: Populate dimension data
-- Substations: 50, Feeders: 2000, Transformers: 20000, Meters: 100000
-- =====================================================================

USE DATABASE AMI_DEMO;
USE SCHEMA AMI_CURATED;
USE WAREHOUSE AMI_LOAD_WH;

-- 4 territories with representative timezones
-- Substations (50): distributed across territories
INSERT INTO SUBSTATION
SELECT
  'SUB-' || LPAD(SEQ4(),4,'0')        AS SUBSTATION_ID,
  'Substation ' || SEQ4()             AS SUBSTATION_NAME,
  CASE MOD(SEQ4(),4) WHEN 0 THEN 'NE' WHEN 1 THEN 'SE' WHEN 2 THEN 'MW' ELSE 'W' END AS UTILITY_TERRITORY,
  30 + UNIFORM(0,15,RANDOM())         AS LAT,
  -120 + UNIFORM(0,45,RANDOM())       AS LON
FROM TABLE(GENERATOR(ROWCOUNT => 50));

-- Feeders (2000): 40 per substation on avg
INSERT INTO FEEDER
SELECT
  'FDR-' || LPAD(SEQ4(),5,'0')  AS FEEDER_ID,
  s.SUBSTATION_ID,
  s.UTILITY_TERRITORY,
  CASE MOD(SEQ4(),3) WHEN 0 THEN 4.16 WHEN 1 THEN 13.2 ELSE 34.5 END AS VOLTAGE_KV
FROM TABLE(GENERATOR(ROWCOUNT => 2000)) g
JOIN (SELECT SUBSTATION_ID, UTILITY_TERRITORY, ROW_NUMBER() OVER (ORDER BY SUBSTATION_ID) rn FROM SUBSTATION) s
  ON s.rn = MOD(SEQ4(),50) + 1;

-- Transformers (20000): 10 per feeder
INSERT INTO TRANSFORMER
SELECT
  'XFM-' || LPAD(SEQ4(),6,'0')  AS TRANSFORMER_ID,
  f.FEEDER_ID,
  CASE MOD(SEQ4(),4) WHEN 0 THEN 25 WHEN 1 THEN 50 WHEN 2 THEN 100 ELSE 250 END AS KVA_RATING,
  CASE MOD(SEQ4(),2) WHEN 0 THEN 'SINGLE' ELSE 'THREE' END AS PHASE
FROM TABLE(GENERATOR(ROWCOUNT => 20000)) g
JOIN (SELECT FEEDER_ID, ROW_NUMBER() OVER (ORDER BY FEEDER_ID) rn FROM FEEDER) f
  ON f.rn = MOD(SEQ4(),2000) + 1;

-- Service points (100000): 5 per transformer
INSERT INTO SERVICE_POINT
SELECT
  'SP-' || LPAD(SEQ4(),6,'0')   AS SERVICE_POINT_ID,
  'ADDR-' || LPAD(SEQ4(),6,'0') AS ADDRESS_ID,
  CASE
    WHEN UNIFORM(0,100,RANDOM()) < 80 THEN 'RES'
    WHEN UNIFORM(0,100,RANDOM()) < 95 THEN 'SMB'
    ELSE 'CNI'
  END                           AS PREMISE_TYPE,
  x.FEEDER_ID,
  x.TRANSFORMER_ID,
  f.UTILITY_TERRITORY,
  30 + UNIFORM(0,15,RANDOM()),
  -120 + UNIFORM(0,45,RANDOM())
FROM TABLE(GENERATOR(ROWCOUNT => 100000)) g
JOIN (SELECT TRANSFORMER_ID, FEEDER_ID, ROW_NUMBER() OVER (ORDER BY TRANSFORMER_ID) rn FROM TRANSFORMER) x
  ON x.rn = MOD(SEQ4(),20000) + 1
JOIN FEEDER f ON f.FEEDER_ID = x.FEEDER_ID;

-- Meters (100000): 1:1 with service points
INSERT INTO METER
SELECT
  'MTR-' || LPAD(SP.rn, 6, '0') AS METER_ID,
  SP.SERVICE_POINT_ID,
  CASE SP.PREMISE_TYPE
    WHEN 'RES' THEN 'RES'
    WHEN 'SMB' THEN 'SMB'
    ELSE 'CNI'
  END AS METER_TYPE,
  CASE WHEN UNIFORM(0,100,RANDOM()) < 3 THEN TRUE ELSE FALSE END AS HAS_DER,
  DATEADD(day, -UNIFORM(365,3650,RANDOM()), CURRENT_DATE()) AS INSTALL_DATE,
  'ACTIVE' AS STATUS,
  SP.UTILITY_TERRITORY,
  CASE SP.UTILITY_TERRITORY
    WHEN 'NE' THEN 'America/New_York'
    WHEN 'SE' THEN 'America/New_York'
    WHEN 'MW' THEN 'America/Chicago'
    ELSE         'America/Los_Angeles'
  END AS TIMEZONE,
  'FW-' || TO_CHAR(MOD(ABS(HASH(SP.SERVICE_POINT_ID)),4) + 1) || '.0' AS FIRMWARE_VERSION
FROM (
  SELECT SERVICE_POINT_ID, PREMISE_TYPE, UTILITY_TERRITORY,
         ROW_NUMBER() OVER (ORDER BY SERVICE_POINT_ID) AS rn
  FROM SERVICE_POINT
) SP;

-- Customers (1:1 with meters, 5% vacancy rate)
INSERT INTO CUSTOMER
SELECT
  'CUST-' || LPAD(rn,6,'0')    AS CUSTOMER_ID,
  'CIS-' || LPAD(rn,6,'0')     AS CIS_ACCOUNT_ID,
  SEGMENT,
  RATE_PLAN_ID,
  DATEADD(day, -UNIFORM(30,1800,RANDOM()), CURRENT_DATE()) AS START_DATE,
  NULL AS END_DATE
FROM (
  SELECT
    ROW_NUMBER() OVER (ORDER BY SERVICE_POINT_ID) AS rn,
    CASE PREMISE_TYPE WHEN 'RES' THEN 'RESIDENTIAL' WHEN 'SMB' THEN 'SMALL_BUSINESS' ELSE 'COMMERCIAL' END AS SEGMENT,
    CASE
      WHEN UNIFORM(0,100,RANDOM()) < 40 THEN 'RP-FLAT'
      WHEN UNIFORM(0,100,RANDOM()) < 90 THEN 'RP-TOU3'
      ELSE                                    'RP-CPP'
    END AS RATE_PLAN_ID
  FROM SERVICE_POINT
) s
WHERE UNIFORM(0,100,RANDOM()) > 5;  -- ~5% vacant

-- SCD2 link: current membership for all meters (assume permanent for demo)
INSERT INTO METER_SERVICE_POINT_LINK
SELECT
  m.METER_ID,
  m.SERVICE_POINT_ID,
  c.CUSTOMER_ID,
  DATEADD(year, -1, CURRENT_DATE())::TIMESTAMP_NTZ AS EFFECTIVE_FROM,
  NULL AS EFFECTIVE_TO,
  TRUE AS IS_CURRENT
FROM METER m
LEFT JOIN CUSTOMER c
  ON c.CUSTOMER_ID = 'CUST-' || SUBSTR(m.METER_ID, 5);
