-- =====================================================================
-- Phase 6: Observability - pipeline audit, DMFs, SLA + DQ metrics
-- =====================================================================

USE DATABASE AMI_DEMO;
USE SCHEMA AMI_OBSERVABILITY;

-- ---- Manual pipeline-run audit (stored proc / task log) --------------
CREATE OR REPLACE TABLE PIPELINE_RUN_AUDIT (
  PIPELINE_NAME    VARCHAR       NOT NULL,
  RUN_ID           VARCHAR       NOT NULL,
  START_TIME       TIMESTAMP_NTZ,
  END_TIME         TIMESTAMP_NTZ,
  STATUS           VARCHAR,        -- RUNNING | SUCCESS | FAILED
  ROWS_PROCESSED   NUMBER,
  ERROR_COUNT      NUMBER,
  MESSAGE          VARCHAR
);

-- ---- Convenience view over DT refresh history ------------------------
-- Rolls up all AMI_* dynamic table refresh history from INFORMATION_SCHEMA
CREATE OR REPLACE VIEW V_DT_REFRESH_HISTORY AS
SELECT
  NAME AS DYNAMIC_TABLE_NAME,
  SCHEMA_NAME,
  DATABASE_NAME,
  STATE,
  DATA_TIMESTAMP,
  REFRESH_START_TIME,
  REFRESH_END_TIME,
  DATEDIFF(second, REFRESH_START_TIME, REFRESH_END_TIME) AS DURATION_SEC,
  REFRESH_ACTION,
  STATISTICS
FROM TABLE(AMI_DEMO.INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
  DATA_TIMESTAMP_START => DATEADD(day, -7, CURRENT_TIMESTAMP()),
  DATA_TIMESTAMP_END   => CURRENT_TIMESTAMP()
));

-- ---- Ingestion SLA metrics (dynamic table) ---------------------------
CREATE OR REPLACE DYNAMIC TABLE DT_INGESTION_SLA_METRICS
  TARGET_LAG = '15 minutes'
  WAREHOUSE = AMI_DT_WH
AS
SELECT
  DATE_TRUNC('day', READ_TS)::DATE AS DATE_KEY,
  UTILITY_TERRITORY,
  COUNT(*)                                                          AS TOTAL_READS,
  MAX(INGESTION_LAG_SEC)/60                                         AS MAX_INGESTION_LAG_MIN,
  (AVG(IFF(INGESTION_LAG_SEC <= 900, 1, 0)) * 100)::NUMBER(5,2)     AS PCT_ARRIVED_WITHIN_15MIN,
  COUNT_IF(INGESTION_LAG_SEC > 900)                                 AS LATE_ARRIVAL_COUNT,
  COUNT_IF(INGESTION_LAG_SEC > 3600)                                AS VERY_LATE_ARRIVAL_COUNT
FROM AMI_CURATED.INTERVAL_READ_15MIN
GROUP BY DATE_TRUNC('day', READ_TS)::DATE, UTILITY_TERRITORY;

-- ---- Data quality metrics (dynamic table) ----------------------------
CREATE OR REPLACE DYNAMIC TABLE DT_DATA_QUALITY_METRICS
  TARGET_LAG = '30 minutes'
  WAREHOUSE = AMI_DT_WH
AS
SELECT
  DATE_TRUNC('day', READ_TS)::DATE AS DATE_KEY,
  UTILITY_TERRITORY,
  COUNT(*)                                                                  AS TOTAL_READS,
  (COUNT_IF(VEE_STATUS='VALID')/COUNT(*)*100)::NUMBER(5,2)                  AS VEE_PASS_RATE,
  COUNT_IF(VEE_STATUS='ESTIMATED')                                          AS ESTIMATED_INTERVALS,
  COUNT_IF(VEE_STATUS='FAILED')                                             AS FAILED_INTERVALS,
  (96 * COUNT(DISTINCT METER_ID) - COUNT(*))                                AS MISSING_INTERVALS,
  (COUNT(*)/(96.0 * COUNT(DISTINCT METER_ID)) * 100)::NUMBER(5,2)           AS COMPLETENESS_PCT
FROM AMI_CURATED.INTERVAL_READ_15MIN
GROUP BY DATE_TRUNC('day', READ_TS)::DATE, UTILITY_TERRITORY;

-- ---- Data Metric Functions with automatic anomaly detection ----------
-- Row count + freshness on RAW and canonical
ALTER TABLE AMI_CURATED.INTERVAL_READ_15MIN SET
  DATA_METRIC_SCHEDULE = '15 MINUTE';

ALTER TABLE AMI_CURATED.INTERVAL_READ_15MIN
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE AMI_CURATED.INTERVAL_READ_15MIN
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (INGESTED_AT);

ALTER TABLE AMI_RAW.INTERVAL_READ_15MIN_RAW SET
  DATA_METRIC_SCHEDULE = '15 MINUTE';

ALTER TABLE AMI_RAW.INTERVAL_READ_15MIN_RAW
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE AMI_RAW.INTERVAL_READ_15MIN_RAW
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (INGESTED_AT);

-- ---- Unified observability view --------------------------------------
CREATE OR REPLACE VIEW V_AMI_OBSERVABILITY_DASHBOARD AS
SELECT
  sla.DATE_KEY,
  sla.UTILITY_TERRITORY,
  sla.TOTAL_READS,
  sla.MAX_INGESTION_LAG_MIN,
  sla.PCT_ARRIVED_WITHIN_15MIN,
  sla.LATE_ARRIVAL_COUNT,
  dq.VEE_PASS_RATE,
  dq.ESTIMATED_INTERVALS,
  dq.FAILED_INTERVALS,
  dq.MISSING_INTERVALS,
  dq.COMPLETENESS_PCT
FROM AMI_OBSERVABILITY.DT_INGESTION_SLA_METRICS sla
FULL OUTER JOIN AMI_OBSERVABILITY.DT_DATA_QUALITY_METRICS dq
  ON sla.DATE_KEY = dq.DATE_KEY
 AND sla.UTILITY_TERRITORY = dq.UTILITY_TERRITORY;

-- ---- SLA Breach alert -------------------------------------------------
CREATE OR REPLACE ALERT AMI_SLA_BREACH
  WAREHOUSE = AMI_QUERY_WH
  SCHEDULE = '15 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM AMI_OBSERVABILITY.DT_INGESTION_SLA_METRICS
    WHERE DATE_KEY = CURRENT_DATE()
      AND PCT_ARRIVED_WITHIN_15MIN < 95
  ))
  THEN
    INSERT INTO AMI_OBSERVABILITY.PIPELINE_RUN_AUDIT
    VALUES ('SLA_BREACH_ALERT', UUID_STRING(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
            'ALERT', 0, 1, 'SLA breach: ingestion < 95% within 15-min window');
