-- =====================================================================
-- Channel-aware Dynamic Tables (long-form grain)
-- ---------------------------------------------------------------------
-- These DTs operate on the channel-keyed grain. Each channel is
-- aggregated with the rule declared in METER_CHANNEL.AGGREGATION
-- (SUM for energy channels, MAX for demand, AVG for voltage).
-- =====================================================================

USE DATABASE AMI_DEMO;
USE SCHEMA AMI_CURATED;

-- Hourly rollup per (METER_ID, CHANNEL_CODE)
CREATE OR REPLACE DYNAMIC TABLE DT_CHANNEL_HOURLY_ROLLUP
  TARGET_LAG = '15 minutes'
  WAREHOUSE = AMI_DT_WH
AS
SELECT
  c.METER_ID,
  c.CHANNEL_CODE,
  c.UOM,
  DATE_TRUNC('hour', c.READ_TS) AS ROLLUP_TS,
  c.UTILITY_TERRITORY,
  SUM(CASE WHEN mc.AGGREGATION = 'SUM' THEN c.VALUE END)::NUMBER(16,4) AS VALUE_SUM,
  MAX(CASE WHEN mc.AGGREGATION = 'MAX' THEN c.VALUE END)::NUMBER(16,4) AS VALUE_MAX,
  MIN(CASE WHEN mc.AGGREGATION = 'MIN' THEN c.VALUE END)::NUMBER(16,4) AS VALUE_MIN,
  AVG(CASE WHEN mc.AGGREGATION = 'AVG' THEN c.VALUE END)::NUMBER(16,4) AS VALUE_AVG,
  -- Resolve to the canonical value using the channel's aggregation rule
  CASE mc.AGGREGATION
    WHEN 'SUM' THEN SUM(c.VALUE)
    WHEN 'MAX' THEN MAX(c.VALUE)
    WHEN 'MIN' THEN MIN(c.VALUE)
    WHEN 'AVG' THEN AVG(c.VALUE)
  END::NUMBER(16,4) AS CANONICAL_VALUE,
  COUNT(*) AS SOURCE_INTERVAL_COUNT,
  4 AS EXPECTED_INTERVAL_COUNT,
  (COUNT(*)/4.0 * 100)::NUMBER(5,2) AS COMPLETENESS_PCT,
  (SUM(CASE WHEN c.VEE_STATUS='VALID' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0)*100)::NUMBER(5,2) AS VEE_PASS_PCT
FROM AMI_CURATED.INTERVAL_READ_CHANNEL c
JOIN AMI_CURATED.METER_CHANNEL mc
  ON mc.METER_ID = c.METER_ID AND mc.CHANNEL_CODE = c.CHANNEL_CODE
GROUP BY c.METER_ID, c.CHANNEL_CODE, c.UOM, mc.AGGREGATION,
         DATE_TRUNC('hour', c.READ_TS), c.UTILITY_TERRITORY;


-- Daily rollup per (METER_ID, CHANNEL_CODE), built on hourly
CREATE OR REPLACE DYNAMIC TABLE DT_CHANNEL_DAILY_ROLLUP
  TARGET_LAG = '30 minutes'
  WAREHOUSE = AMI_DT_WH
AS
SELECT
  METER_ID,
  CHANNEL_CODE,
  UOM,
  DATE_TRUNC('day', ROLLUP_TS) AS ROLLUP_DATE,
  UTILITY_TERRITORY,
  SUM(VALUE_SUM)::NUMBER(18,4) AS VALUE_SUM,
  MAX(VALUE_MAX)::NUMBER(18,4) AS VALUE_MAX,
  MIN(VALUE_MIN)::NUMBER(18,4) AS VALUE_MIN,
  AVG(VALUE_AVG)::NUMBER(18,4) AS VALUE_AVG,
  SUM(SOURCE_INTERVAL_COUNT) AS SOURCE_INTERVAL_COUNT,
  96 AS EXPECTED_INTERVAL_COUNT,
  (SUM(SOURCE_INTERVAL_COUNT)/96.0*100)::NUMBER(5,2) AS COMPLETENESS_PCT,
  AVG(VEE_PASS_PCT)::NUMBER(5,2) AS VEE_PASS_PCT
FROM AMI_CURATED.DT_CHANNEL_HOURLY_ROLLUP
GROUP BY METER_ID, CHANNEL_CODE, UOM,
         DATE_TRUNC('day', ROLLUP_TS), UTILITY_TERRITORY;


-- ---- Backward-compat wide view over the long-form fact ---------------
-- Existing DTs (DT_HOURLY_ROLLUP, TOU, billing) and the dashboard continue
-- to read the wide shape via this view.
CREATE OR REPLACE VIEW AMI_CURATED.V_INTERVAL_READ_15MIN_WIDE AS
SELECT
  METER_ID,
  READ_TS,
  MAX(IFF(CHANNEL_CODE='KWH_DEL',  VALUE, NULL))::NUMBER(14,4) AS KWH_DELIVERED,
  MAX(IFF(CHANNEL_CODE='KWH_REC',  VALUE, NULL))::NUMBER(14,4) AS KWH_RECEIVED,
  MAX(IFF(CHANNEL_CODE='KW_DEM',   VALUE, NULL))::NUMBER(10,4) AS DEMAND_KW,
  MAX(IFF(CHANNEL_CODE='VOLT_AVG', VALUE, NULL))::NUMBER(6,2)  AS VOLTAGE_V,
  ANY_VALUE(QUALITY_FLAG)      AS QUALITY_FLAG,
  ANY_VALUE(VEE_STATUS)        AS VEE_STATUS,
  ANY_VALUE(ESTIMATION_METHOD) AS ESTIMATION_METHOD,
  ANY_VALUE(EVENT_ID)          AS EVENT_ID,
  ANY_VALUE(UTILITY_TERRITORY) AS UTILITY_TERRITORY,
  ANY_VALUE(SOURCE_FILE)       AS SOURCE_FILE,
  ANY_VALUE(INGESTED_AT)       AS INGESTED_AT,
  ANY_VALUE(INGESTION_LAG_SEC) AS INGESTION_LAG_SEC
FROM AMI_CURATED.INTERVAL_READ_CHANNEL
GROUP BY METER_ID, READ_TS;
