-- =====================================================================
-- AMI 2.0 Snowsight Dashboard - pre-built queries for 4 tabs
-- Tab 1: Ingestion live feed
-- Tab 2: Data quality
-- Tab 3: Billing readiness
-- Tab 4: Anomalies
-- =====================================================================

-- ---------------- Tab 1: Ingestion ------------------------------------
-- Reads per hour by territory
SELECT DATE_TRUNC('hour', READ_TS) AS HR, UTILITY_TERRITORY, COUNT(*) AS READS
FROM AMI_DEMO.AMI_CURATED.INTERVAL_READ_15MIN
WHERE READ_TS >= DATEADD(day, -7, CURRENT_TIMESTAMP())
GROUP BY HR, UTILITY_TERRITORY
ORDER BY HR, UTILITY_TERRITORY;

-- Ingestion SLA heatmap (daily)
SELECT DATE_KEY, UTILITY_TERRITORY, PCT_ARRIVED_WITHIN_15MIN,
       LATE_ARRIVAL_COUNT, MAX_INGESTION_LAG_MIN
FROM AMI_DEMO.AMI_OBSERVABILITY.DT_INGESTION_SLA_METRICS
ORDER BY DATE_KEY DESC, UTILITY_TERRITORY;

-- ---------------- Tab 2: Data Quality ---------------------------------
-- VEE pass rate trend
SELECT DATE_KEY, UTILITY_TERRITORY, VEE_PASS_RATE,
       ESTIMATED_INTERVALS, FAILED_INTERVALS, COMPLETENESS_PCT
FROM AMI_DEMO.AMI_OBSERVABILITY.DT_DATA_QUALITY_METRICS
ORDER BY DATE_KEY DESC, UTILITY_TERRITORY;

-- Completeness by feeder (worst 20 in last 7 days)
SELECT sp.FEEDER_ID, COUNT(DISTINCT i.METER_ID) AS METERS,
       (COUNT(*) / (96.0 * 7.0 * COUNT(DISTINCT i.METER_ID)) * 100)::NUMBER(5,2) AS COMPLETENESS_PCT
FROM AMI_DEMO.AMI_CURATED.INTERVAL_READ_15MIN i
JOIN AMI_DEMO.AMI_CURATED.METER m USING (METER_ID)
JOIN AMI_DEMO.AMI_CURATED.SERVICE_POINT sp USING (SERVICE_POINT_ID)
WHERE i.READ_TS >= DATEADD(day, -7, CURRENT_DATE())
GROUP BY sp.FEEDER_ID
ORDER BY COMPLETENESS_PCT ASC
LIMIT 20;

-- ---------------- Tab 3: Billing Readiness ----------------------------
SELECT START_DATE, COUNT(*) AS total_periods,
       COUNT_IF(IS_BILLING_READY) AS ready,
       (COUNT_IF(IS_BILLING_READY)/COUNT(*) * 100)::NUMBER(5,2) AS pct_ready
FROM AMI_DEMO.AMI_MART.DT_BILLING_PERIOD_CONSUMPTION
GROUP BY START_DATE
ORDER BY START_DATE DESC;

-- Worst 10 unready periods
SELECT BILLING_PERIOD_ID, METER_ID, KWH_TOTAL, COMPLETENESS_PCT, VEE_PASS_PCT
FROM AMI_DEMO.AMI_MART.DT_BILLING_PERIOD_CONSUMPTION
WHERE NOT IS_BILLING_READY
ORDER BY COMPLETENESS_PCT ASC
LIMIT 10;

-- ---------------- Tab 4: Anomalies ------------------------------------
SELECT FEEDER_ID, TS, KWH, FORECAST, LOWER_BOUND, UPPER_BOUND, DISTANCE
FROM AMI_DEMO.AMI_MART.AMI_ANOMALY_EVENTS
WHERE IS_ANOMALY
ORDER BY DISTANCE DESC
LIMIT 50;

-- Anomalies per day
SELECT DATE_TRUNC('day', TS)::DATE AS DAY, COUNT_IF(IS_ANOMALY) AS anomalies
FROM AMI_DEMO.AMI_MART.AMI_ANOMALY_EVENTS
GROUP BY DAY
ORDER BY DAY DESC;
