-- =====================================================================
-- Phase 0: Roles (scaffolded, full grants applied in Phase 8)
-- =====================================================================

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS AMI_OWNER   COMMENT = 'Owns AMI_DEMO DDL';
CREATE ROLE IF NOT EXISTS AMI_ENG     COMMENT = 'Read/write curated + mart';
CREATE ROLE IF NOT EXISTS AMI_ANALYST COMMENT = 'Read mart only';
CREATE ROLE IF NOT EXISTS AMI_OPS     COMMENT = 'Read observability, execute pipeline tasks';
CREATE ROLE IF NOT EXISTS AMI_SHARE   COMMENT = 'Consume AMI_SHARED secure views only';

GRANT ROLE AMI_OWNER   TO ROLE SYSADMIN;
GRANT ROLE AMI_ENG     TO ROLE AMI_OWNER;
GRANT ROLE AMI_ANALYST TO ROLE AMI_ENG;
GRANT ROLE AMI_OPS     TO ROLE AMI_OWNER;
GRANT ROLE AMI_SHARE   TO ROLE AMI_OWNER;

GRANT OWNERSHIP ON DATABASE AMI_DEMO TO ROLE AMI_OWNER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE AMI_DEMO TO ROLE AMI_OWNER COPY CURRENT GRANTS;

GRANT USAGE ON WAREHOUSE AMI_LOAD_WH   TO ROLE AMI_OWNER;
GRANT USAGE ON WAREHOUSE AMI_DT_WH     TO ROLE AMI_OWNER;
GRANT USAGE ON WAREHOUSE AMI_STREAM_WH TO ROLE AMI_OWNER;
GRANT USAGE ON WAREHOUSE AMI_ML_WH     TO ROLE AMI_OWNER;
GRANT USAGE ON WAREHOUSE AMI_QUERY_WH  TO ROLE AMI_OWNER;

GRANT USAGE ON WAREHOUSE AMI_DT_WH    TO ROLE AMI_ENG;
GRANT USAGE ON WAREHOUSE AMI_QUERY_WH TO ROLE AMI_ENG;
GRANT USAGE ON WAREHOUSE AMI_QUERY_WH TO ROLE AMI_ANALYST;
GRANT USAGE ON WAREHOUSE AMI_QUERY_WH TO ROLE AMI_OPS;
