-- =====================================================================
-- Phase 8: Row-access policies, masking, secure views
-- =====================================================================

USE DATABASE AMI_DEMO;
USE SCHEMA AMI_CURATED;

-- ---- Role -> territory map -------------------------------------------
CREATE OR REPLACE TABLE ROLE_TERRITORY_MAP (
  ROLE_NAME         VARCHAR,
  UTILITY_TERRITORY VARCHAR
);

-- Example assignments (extend as needed)
INSERT INTO ROLE_TERRITORY_MAP VALUES
  ('AMI_ANALYST_NE', 'NE'),
  ('AMI_ANALYST_SE', 'SE'),
  ('AMI_ANALYST_MW', 'MW'),
  ('AMI_ANALYST_W',  'W');


-- ---- Row access policy by territory ----------------------------------
CREATE OR REPLACE ROW ACCESS POLICY RAP_TERRITORY
  AS (territory VARCHAR) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ACCOUNTADMIN','SYSADMIN','AMI_OWNER','AMI_ENG','AMI_OPS')
  OR territory IN (
    SELECT UTILITY_TERRITORY FROM AMI_CURATED.ROLE_TERRITORY_MAP
    WHERE ROLE_NAME = CURRENT_ROLE()
  );

ALTER TABLE AMI_CURATED.INTERVAL_READ_15MIN
  ADD ROW ACCESS POLICY RAP_TERRITORY ON (UTILITY_TERRITORY);

ALTER TABLE AMI_CURATED.METER
  ADD ROW ACCESS POLICY RAP_TERRITORY ON (UTILITY_TERRITORY);

-- ---- Masking policy on CIS_ACCOUNT_ID --------------------------------
CREATE OR REPLACE MASKING POLICY MP_CIS_ACCOUNT AS (val VARCHAR) RETURNS VARCHAR ->
  CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','AMI_OWNER','AMI_ENG') THEN val
    ELSE SHA2(val, 256)
  END;

ALTER TABLE AMI_CURATED.CUSTOMER
  MODIFY COLUMN CIS_ACCOUNT_ID SET MASKING POLICY MP_CIS_ACCOUNT;

ALTER TABLE AMI_CURATED.BILLING_PERIOD
  MODIFY COLUMN CIS_ACCOUNT_ID SET MASKING POLICY MP_CIS_ACCOUNT;


-- ---- Secure views in AMI_SHARED --------------------------------------
USE SCHEMA AMI_SHARED;

CREATE OR REPLACE SECURE VIEW V_CIS_BILLING_CONSUMPTION AS
SELECT
  BILLING_PERIOD_ID, CIS_ACCOUNT_ID, SERVICE_POINT_ID, METER_ID,
  START_DATE, END_DATE, KWH_TOTAL, KWH_RECEIVED, KWH_NET,
  MAX_DEMAND_KW, COMPLETENESS_PCT, VEE_PASS_PCT, IS_BILLING_READY
FROM AMI_MART.DT_BILLING_PERIOD_CONSUMPTION;

CREATE OR REPLACE SECURE VIEW V_METER_DAILY_KWH AS
SELECT
  METER_ID, UTILITY_TERRITORY, ROLLUP_TS::DATE AS READ_DATE,
  KWH_DELIVERED, KWH_RECEIVED, MAX_DEMAND_KW,
  COMPLETENESS_PCT, VEE_PASS_PCT
FROM AMI_CURATED.DT_DAILY_ROLLUP;

CREATE OR REPLACE SECURE VIEW V_FEEDER_ANOMALIES AS
SELECT FEEDER_ID, TS, KWH, FORECAST, LOWER_BOUND, UPPER_BOUND,
       IS_ANOMALY, DISTANCE, DETECTED_AT
FROM AMI_MART.AMI_ANOMALY_EVENTS
WHERE IS_ANOMALY;

-- ---- Outbound share scaffold -----------------------------------------
-- Commented out to avoid accidental share creation; enable per deployment
-- CREATE SHARE IF NOT EXISTS AMI_REGULATOR_SHARE;
-- GRANT USAGE ON DATABASE AMI_DEMO TO SHARE AMI_REGULATOR_SHARE;
-- GRANT USAGE ON SCHEMA AMI_SHARED TO SHARE AMI_REGULATOR_SHARE;
-- GRANT SELECT ON ALL SECURE VIEWS IN SCHEMA AMI_SHARED TO SHARE AMI_REGULATOR_SHARE;
